[package]
name = "picture-view"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
sdl2 = "0.35.2"
thiserror = "1.0.35"